### PR TITLE
Mahmut calendar

### PR DESCRIPTION
**Pull request by Cuvoglu**

### CODE REVIEW

**Comment by athinalioga** [comment]
you code looks good but have you created "page" class to put your elements ?

**Comment by Cuvoglu** [comment]
Hi AthenaI missing this part. I write all codes in the codepage. I should create my own in the page class. Thanks for advice.Thank youMahmut 7 Tem 2022 14:51 tarihinde athinalioga ***@***.***> yazdı:
you code looks good but have you created "page" class to put your elements ?

**Review by athinalioga — APPROVED** [review]

**Review by EmirBeyazortu — APPROVED** [review]
Great effort! Congratulations

**Comment by Cuvoglu** [comment]
it is fnish

**Pull request closed without merging**
